"""project型変換

Revision ID: 74b606dc50b3
Revises: 2f9258a6efcf
Create Date: 2026-05-02 12:05:06.940762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b606dc50b3'
down_revision: Union[str, Sequence[str], None] = '2f9258a6efcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=sa.String(),
               type_=sa.Enum('not_started', 'in_progress', 'reviewing', 'completed', 'on_hold', 'cancelled', name='projectstatus'),
               existing_nullable=False)
    op.alter_column('projects', 'priority',
               existing_type=sa.String(),
               type_=sa.Enum('low', 'medium', 'high', name='projectpriority'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('not_started', 'in_progress', 'reviewing', 'completed', 'on_hold', 'cancelled', name='projectstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'priority',
               existing_type=sa.Enum('low', 'medium', 'high', name='projectpriority'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###
