"""modify_projects_table_relation

Revision ID: 811df3221c47
Revises: e7d8f6b0d57e
Create Date: 2026-05-02 19:17:56.883084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811df3221c47'
down_revision: Union[str, Sequence[str], None] = 'e7d8f6b0d57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'pic')
    op.drop_column('projects', 'progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('progress', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('pic', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
