"""projects_table_add_column_and_null_setting

Revision ID: e7d8f6b0d57e
Revises: 74b606dc50b3
Create Date: 2026-05-02 12:20:20.720747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d8f6b0d57e'
down_revision: Union[str, Sequence[str], None] = '74b606dc50b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('pic', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('progress', sa.String(), nullable=True))
    op.alter_column('projects', 'delivery_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'delivery_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('projects', 'progress')
    op.drop_column('projects', 'pic')
    # ### end Alembic commands ###
